[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
upload_protocol = picotool
build_flags =
    -I${platformio.packages_dir}/framework-arduinopico/libraries/tusb-hid/src
